# shellcheck shell=bash
# ai-harness: instruction copies for local mode. Harness-owned: replaced on upgrade.
# Sourced by sync (writes them) and verify (reports a stale one).
#
# Local mode with a tracked AGENTS.md keeps the managed blocks in .agents/AGENTS.local.md, which
# Claude Code imports. Copilot, Cursor, Codex, and Gemini CLI don't read that file, so each enabled
# one gets the harness instructions in a file it reads on its own, next to AGENTS.md (vendor docs,
# checked Oct 2026):
#   copilot  .github/instructions/ai-harness.instructions.md   applyTo "**"; read with AGENTS.md
#            https://code.visualstudio.com/docs/copilot/customization/custom-instructions
#            https://docs.github.com/en/copilot/how-tos/copilot-cli/customize-copilot/add-custom-instructions
#   cursor   .cursor/rules/ai-harness.mdc   alwaysApply: true; read with AGENTS.md (editor and CLI)
#            https://cursor.com/docs/context/rules  https://cursor.com/docs/cli/using
#   codex    AGENTS.override.md   read in place of AGENTS.md in the same directory, so it holds
#            AGENTS.md too: https://learn.chatgpt.com/docs/agent-configuration/agents-md
#   gemini   GEMINI.md   imports .agents/AGENTS.local.md (@ path relative to the file); sync lists
#            it with AGENTS.md in context.fileName: https://geminicli.com/docs/cli/gemini-md/
#            https://geminicli.com/docs/reference/memport/
# Each is untracked, hidden by the exclude block, and holds the marker line below; a file at one
# of these paths without it isn't the harness's and is never touched.
# bash 3.2 and POSIX tools only.

# shellcheck disable=SC2034  # read by the scripts that source this
AGENTS_RULES_COPIES="AGENTS.override.md .cursor/rules/ai-harness.mdc .github/instructions/ai-harness.instructions.md GEMINI.md"
AGENTS_RULES_MARK='<!-- ai-harness: generated by .agents/bin/sync'

# agents_rules_adapter <path>: the adapter a copy is for
agents_rules_adapter() {
  case "$1" in
    AGENTS.override.md) echo codex ;;
    .cursor/*) echo cursor ;;
    .github/*) echo copilot ;;
    GEMINI.md) echo gemini ;;
  esac
}

# agents_rules_tool <path>: the tool's name, for messages
agents_rules_tool() {
  case "$(agents_rules_adapter "$1")" in
    codex) echo Codex ;; cursor) echo Cursor ;; copilot) echo Copilot ;; gemini) echo "Gemini CLI" ;;
  esac
}

# agents_rules_stale_why <path>: why a copy that differs from what sync would write is out of date
agents_rules_stale_why() {
  case "$1" in
    AGENTS.override.md) echo "it's out of date with AGENTS.md or .agents/AGENTS.local.md" ;;
    GEMINI.md) echo "it isn't what sync writes now" ;;
    *) echo "it's out of date with .agents/AGENTS.local.md" ;;
  esac
}

# agents_rules_linked_dir <path>: a directory on the way to the copy is a symlink (a shared rules
# folder, say), so writing there would land outside this project
agents_rules_linked_dir() {
  local d="$1"
  while :; do
    case "$d" in */*) d="${d%/*}" ;; *) return 1 ;; esac
    [ -L "$d" ] && return 0
  done
}

# agents_rules_marked <path>: a regular file in this project holding the marker line, so the
# harness wrote it
agents_rules_marked() {
  [ -f "$1" ] && [ ! -L "$1" ] && ! agents_rules_linked_dir "$1" \
    && grep -q '^<!-- ai-harness: generated by \.agents/bin/sync' "$1" 2>/dev/null
}

# agents_rules_copy <path> <local> <agents>: what the copy at <path> holds, from the harness's
# instructions file <local> (.agents/AGENTS.local.md's content) and the project's <agents>
# (AGENTS.md; only Codex's copy uses it).
agents_rules_copy() {
  local note="Edit .agents/AGENTS.local.md, not this file: .agents/bin/sync rewrites it. -->"
  case "$1" in
    .github/*)
      printf '%s\n' '---' 'applyTo: "**"' 'description: "ai-harness instructions for this clone (local mode): workflow rules, checks, and skills"' '---' \
        "$AGENTS_RULES_MARK for Copilot from .agents/AGENTS.local.md. $note" ''
      awk 1 "$2" ;;
    .cursor/*)
      printf '%s\n' '---' 'description: "ai-harness instructions for this clone (local mode): workflow rules, checks, and skills"' 'alwaysApply: true' '---' \
        "$AGENTS_RULES_MARK for Cursor from .agents/AGENTS.local.md. $note" ''
      awk 1 "$2" ;;
    AGENTS.override.md)
      # Codex reads this in place of AGENTS.md: the project's AGENTS.md first, as it is, then the harness's.
      printf '%s\n' "$AGENTS_RULES_MARK for Codex, which reads this file in place of AGENTS.md: AGENTS.md as the project tracks it, then .agents/AGENTS.local.md. Edit those, not this file: .agents/bin/sync rewrites it. -->" ''
      if [ -f "$3" ]; then awk 1 "$3"; echo; fi
      awk 1 "$2" ;;
    GEMINI.md)
      printf '%s\n' "$AGENTS_RULES_MARK for Gemini CLI: it imports .agents/AGENTS.local.md. $note" '' \
        '@./.agents/AGENTS.local.md' ;;
  esac
}

# agents_rules_exclude <prefix>: exclude-block lines for the copies sync wrote (marked, untracked).
# Uses sync's tracked().
agents_rules_exclude() {
  local p
  for p in $AGENTS_RULES_COPIES; do
    if agents_rules_marked "$p" && ! tracked "$p"; then echo "/$1$p"; fi
  done
}

# agents_rules_gemini_reads: Gemini CLI loads GEMINI.md in this project. That's its default, and
# sync lists GEMINI.md in an untracked .gemini/settings.json; a tracked one is the project's and
# may set context.fileName to other files only. Uses sync's tracked() and $PY.
agents_rules_gemini_reads() {
  { [ -f .gemini/settings.json ] && tracked .gemini/settings.json; } || return 0
  if [ -z "$PY" ]; then
    # Without python3, roughly: no fileName key (the default), or one with GEMINI.md named.
    ! grep -q '"fileName"' .gemini/settings.json || grep -q '"GEMINI\.md"' .gemini/settings.json
    return
  fi
  "$PY" - .gemini/settings.json <<'PYEOF' 2>/dev/null
import json, sys
try:
    obj = json.load(open(sys.argv[1], encoding="utf-8"))
except (OSError, ValueError):
    sys.exit(1)
ctx = obj.get("context") if isinstance(obj, dict) else None
fn = ctx.get("fileName") if isinstance(ctx, dict) else None
sys.exit(0 if fn is None or fn == "GEMINI.md" or (isinstance(fn, list) and "GEMINI.md" in fn) else 1)
PYEOF
}

# agents_rules_sync: sync's step. Writes each wanted copy (local mode, a tracked AGENTS.md so the
# blocks are in .agents/AGENTS.local.md, the adapter on) from $WORK/step2.md, the rendered blocks
# file; removes a marked, untracked copy that's no longer wanted (team mode, AGENTS.md untracked,
# the adapter off, Gemini not reading GEMINI.md); warns for a tool whose path is taken. Uses
# sync's LOCAL, AGENTS_FILE, ADAPTERS, CHECK, WORK, put, drift, say, warn, and tracked.
agents_rules_sync() {
  local p a want missed=""
  for p in $AGENTS_RULES_COPIES; do
    a="$(agents_rules_adapter "$p")"
    want=0
    if [ "$LOCAL" -eq 1 ] && [ "$AGENTS_FILE" != AGENTS.md ]; then
      case " $ADAPTERS " in *" $a "*) want=1 ;; esac
    fi
    if [ "$want" -eq 1 ]; then
      if agents_rules_linked_dir "$p"; then
        missed="$missed link:$p"
        continue
      fi
      if tracked "$p" || { { [ -e "$p" ] || [ -L "$p" ]; } && ! agents_rules_marked "$p"; }; then
        missed="$missed $p"
        continue
      fi
      if [ "$a" = gemini ] && ! agents_rules_gemini_reads; then
        missed="$missed gemini-settings"
        want=0
      else
        agents_rules_copy "$p" "$WORK/step2.md" AGENTS.md > "$WORK/rules.copy"
        put "$p" "$WORK/rules.copy"
        # Codex stops reading instruction files at project_doc_max_bytes (32 KiB by default), and
        # the harness's part comes last.
        if [ "$a" = codex ] && [ "$CHECK" -eq 0 ] && [ "$(wc -c < "$WORK/rules.copy")" -gt 32768 ]; then
          warn "$p is over 32 KiB, Codex's default project_doc_max_bytes, so Codex may cut off the harness rules at its end; raise project_doc_max_bytes in your Codex config, or shorten AGENTS.md or .agents/AGENTS.local.md"
        fi
        continue
      fi
    fi
    if agents_rules_marked "$p" && tracked "$p"; then
      # A local-mode copy that got committed: every clone's tool reads it (Codex in place of AGENTS.md).
      [ "$CHECK" -eq 1 ] || warn "$p is tracked, but it's a copy sync wrote for local mode, and $(agents_rules_tool "$p") reads it in every clone; remove it: git rm -- $p (then commit)"
    elif agents_rules_marked "$p"; then
      if [ "$CHECK" -eq 1 ]; then drift "$p (remove)"; continue; fi
      rm -f "$p"
      case "$p" in */*) rmdir -p "${p%/*}" 2>/dev/null || true ;; esac
      CHANGED=1
      say "removed $p (no longer needed)"
    fi
  done
  { [ -n "$missed" ] && [ "$CHECK" -eq 0 ]; } || return 0
  for p in $missed; do
    if [ "$p" = gemini-settings ]; then
      warn "the project tracks AGENTS.md and .gemini/settings.json, whose context.fileName leaves out GEMINI.md, so Gemini CLI won't see the harness rules in this clone; its hooks still enforce the checks and policy where they run"
      continue
    fi
    case "$p" in
      link:*)
        p="${p#link:}"
        warn "the project tracks AGENTS.md and a directory holding $p is a symlink, so sync doesn't write there and $(agents_rules_tool "$p") won't see the harness rules in this clone; its hooks still enforce the checks and policy where they run"
        continue ;;
    esac
    a="$(agents_rules_tool "$p")"
    if tracked "$p"; then
      warn "the project tracks AGENTS.md and $p, so $a won't see the harness rules in this clone; its hooks still enforce the checks and policy where they run"
    else
      warn "the project tracks AGENTS.md and $p wasn't made by sync, so $a won't see the harness rules in this clone (move that file aside and re-run sync to get them); its hooks still enforce the checks and policy where they run"
    fi
  done
}
